### ISSUE TITLE
RE: upload and tag for sequencing data

### ISSUE THREAD

**Issue by vortexing** [FredHutch/s3tagcrawler#1]
I uploaded and tagged new sequencing data today and all appears to be a-ok!  Just wanted to send a view things I noticed.  

grablargenode appears to no longer ok by default, so I had to grabnode, then specified 16 cores, 50GB and 1 day.  With transfers to s3, how does one decide how much memory the process needs?  Any guidance there from what is Best Practices/being considerate, or from job speed and estimating how much memory you need based on the total size of data you will be transferring in one go?

Also, I might consider adding a suggestion in the readme to write the output to a file so it can be reviewed later. 

Last thing is that I can only spot check the tagging, not really look at what's in the bucket and double check tags.  I think some future tool from someone/somewhere that would let me in a fairly straightforward/friendly way peruse the data in my bucket by tag rather than be prefix just to make sure there aren't any things tagged the wrong way or with erroneously duplicated tag sets.  Someday!

The tool is great though, thanks!

**Comment by dtenenba** [comment]
Hi @vortexing ,

Sorry, I did not see this till now. I assumed that I would get a notification of an issue filed in any repo I created, but I guess it doesn't work that way! I've opted to "Watch" the repo so hopefully I will see these in the future.

I will update the docs to no longer suggest `grablargenode`. 

Memorywise, anything >= 32GB is probably fine.

Unfortunately you can't actually search S3 by tag. At least not yet. 
However, we could certainly have some process that crawls all the files in your bucket once or twice a day and retrieves the tags of each, which would allow us to create a database where you can search by tag and it returns s3 urls. 

Leaving this open until I make those doc changes...

**Comment by vortexing** [comment]
There is not enough change in my one S3 bucket to warrant a live search by tag.  An occasional snapshot (or maybe one I could generate when I need it rather than constantly updated), of all files in the bucket with the prefix and assigned tag values would be great.  More as a check that everything uploaded correctly than a live-on-the-fly tool.  This would be helpful for checking to see if a Globus job failed because it couldn't find the file, or if the tags were off/different from what I sent in the manifest to Globus.  A place I could just go look up an old query is likely fine.  

An alternative idea for JUST confirming an upload/tag process would be to generate a query of only the files in the manifest and return to me the result from querying for tags for those files.  Then I can have a record that everything went up ok.  Maybe I'm paranoid though.

**Comment by vortexing** [comment]
@dtenenba I have a few jobs that failed in Globus for no obvious reason, b/c their S3 transfer tool doesn't give much feedback.  The data did not transfer successfully into Globus, and I suspect that this is not because the prefix is wrong, but rather b/c I put those data up there before your upload and tag process existed.  

Now I need to figure out if the tags of files with those prefixes are wrong or absent and if they are, manually fix them.  

This is likely how this process will work moving forward for tag-repair and job troubleshooting.  Would it be less of a crazy ask to have a process where I could provide a prefix and it return the tags of entities with that same prefix, then allow me to manually type in what they SHOULD be and have it update those tags?  

That seems less insane than a whole bucket tag search.  Maybe it's not.

**Comment by vortexing** [comment]
all of this is done.
